model {
  file: "model.sdf"
}
name: "Dino_4"
description: "Dino 4"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "VITRUVIUS"
}
annotations {
  key: "mpn"
  value: "dino4"
}
annotations {
  key: "sku"
  value: "DINO4"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Action Figures"
}
