---
- ros_topic_name: "camera/image"
  gz_topic_name: "/world/map/model/iris/link/tilt_link/sensor/camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
