# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - learm_arm_controller

  learm_arm_controller:
    type: FollowJointTrajectory
    joints:
      - shoulder_pan
      - shoulder_lift
      - elbow
      - wrist_flex
      - wrist_roll
    action_ns: follow_joint_trajectory
    default: true