# Default initial positions for iris_with_arm's ros2_control fake system

initial_positions:
  arm_Elbow: 0
  arm_Gripper: 0
  arm_Shoulder_Pitch: 0
  arm_Shoulder_Rotation: 0
  arm_Wrist_Pitch: 0
  arm_Wrist_Roll: 0