"""
Generate a sdf model for the SO-ARM100.

Usage

  python ./generate_sdf.py

Dependencies

  ros2 pkg `so_arm_100_description`
  
  - robot description package for the SO-AMR100 robotic arm
  - https://github.com/brukg/SO-100-arm

Notes

  - `so_arm_100.urdf.xacro` is an xacro file used to assemble the urdf
    for the arm. It depends on the robot description `so_arm_100_description`.
  - `intitial_positions.yaml` is used to configure the initial positions
    of the SO-ARM100 joints.
  - `model.sdf` is generated by this script and should not be edited directly.

"""

import subprocess
import tempfile
import xacro

from lxml import etree
from pathlib import Path


def generate_sdf_model():
    # output file
    sdf_file = Path("model.sdf")

    # input files
    initial_positions_file = Path("initial_positions.yaml")
    xacro_file = Path("so_arm_100.urdf.xacro")

    # xacro parameters
    prefix = "arm_"
    use_sim = "true"
    use_topic_hardware_interface = "true"
    ros2_controllers_file = Path("")

    xacro_doc = xacro.process_file(
        xacro_file,
        mappings={
            "prefix": prefix,
            "initial_positions_file": str(initial_positions_file),
            "use_sim": use_sim,
            "use_topic_hardware_interface": use_topic_hardware_interface,
            "ros2_controllers_file": str(ros2_controllers_file),
        },
    )

    robot_desc = xacro_doc.toprettyxml(indent="  ")

    temp_file = tempfile.NamedTemporaryFile(delete=False, suffix=".urdf")
    temp_file_name = temp_file.name

    with open(temp_file_name, "w") as file:
        file.write(str(robot_desc))

    # Create sdf from urdf
    with subprocess.Popen(
        ["gz", "sdf", "-p", f"{temp_file_name}"], stdout=subprocess.PIPE
    ) as proc:
        sdf_doc = etree.fromstring(proc.stdout.read())
        model_sdf = etree.tostring(sdf_doc, pretty_print=True).decode()

    # reverse the conversion by gz sdf of the prefix package:// to model://
    # replace model:// prefix with package location
    replace_str = f"model://so_arm_100_description/models"
    with_str = f"package://so_arm_100_description/models"
    model_sdf = model_sdf.replace(replace_str, with_str)

    with open(sdf_file, "w") as file:
        file.write(str(model_sdf))


def main():
    generate_sdf_model()


if __name__ == "__main__":
    main()
